// Code generated by protoc-gen-go.
// source: Command.proto
// DO NOT EDIT!

/*
Package Report is a generated protocol buffer package.

It is generated from these files:
	Command.proto

It has these top-level messages:
	Command
	ControlReport
*/
package Report

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Command_CommandType int32

const (
	// up message
	Command_CMT_INVALID          Command_CommandType = 0
	Command_CMT_REPLOGIN         Command_CommandType = 257
	Command_CMT_REPONLINE        Command_CommandType = 258
	Command_CMT_REPWARNUP        Command_CommandType = 259
	Command_CMT_REPMACK          Command_CommandType = 260
	Command_CMT_REPDEVICELIST    Command_CommandType = 261
	Command_CMT_REPOPFEEDBACK    Command_CommandType = 262
	Command_CMT_REPADDDELDEVICE  Command_CommandType = 263
	Command_CMT_REPSETDEVICENAME Command_CommandType = 264
	// down message
	Command_CMT_REQLOGIN         Command_CommandType = 33025
	Command_CMT_REQONLINE        Command_CommandType = 33026
	Command_CMT_REQWARNUP        Command_CommandType = 33027
	Command_CMT_REQDEVICELIST    Command_CommandType = 33029
	Command_CMT_REQOP            Command_CommandType = 33030
	Command_CMT_REQSETDEVICENAME Command_CommandType = 33032
	Command_CMT_REQCHANGEPASSWD  Command_CommandType = 33033
)

var Command_CommandType_name = map[int32]string{
	0:     "CMT_INVALID",
	257:   "CMT_REPLOGIN",
	258:   "CMT_REPONLINE",
	259:   "CMT_REPWARNUP",
	260:   "CMT_REPMACK",
	261:   "CMT_REPDEVICELIST",
	262:   "CMT_REPOPFEEDBACK",
	263:   "CMT_REPADDDELDEVICE",
	264:   "CMT_REPSETDEVICENAME",
	33025: "CMT_REQLOGIN",
	33026: "CMT_REQONLINE",
	33027: "CMT_REQWARNUP",
	33029: "CMT_REQDEVICELIST",
	33030: "CMT_REQOP",
	33032: "CMT_REQSETDEVICENAME",
	33033: "CMT_REQCHANGEPASSWD",
}
var Command_CommandType_value = map[string]int32{
	"CMT_INVALID":          0,
	"CMT_REPLOGIN":         257,
	"CMT_REPONLINE":        258,
	"CMT_REPWARNUP":        259,
	"CMT_REPMACK":          260,
	"CMT_REPDEVICELIST":    261,
	"CMT_REPOPFEEDBACK":    262,
	"CMT_REPADDDELDEVICE":  263,
	"CMT_REPSETDEVICENAME": 264,
	"CMT_REQLOGIN":         33025,
	"CMT_REQONLINE":        33026,
	"CMT_REQWARNUP":        33027,
	"CMT_REQDEVICELIST":    33029,
	"CMT_REQOP":            33030,
	"CMT_REQSETDEVICENAME": 33032,
	"CMT_REQCHANGEPASSWD":  33033,
}

func (x Command_CommandType) String() string {
	return proto.EnumName(Command_CommandType_name, int32(x))
}

type Command_Param_ParaType int32

const (
	Command_Param_Null   Command_Param_ParaType = 0
	Command_Param_UINT8  Command_Param_ParaType = 1
	Command_Param_UINT16 Command_Param_ParaType = 2
	Command_Param_UINT32 Command_Param_ParaType = 3
	Command_Param_UINT64 Command_Param_ParaType = 4
	Command_Param_FLOAT  Command_Param_ParaType = 16
	Command_Param_DOUBLE Command_Param_ParaType = 17
	Command_Param_STRING Command_Param_ParaType = 32
	Command_Param_BYTES  Command_Param_ParaType = 33
)

var Command_Param_ParaType_name = map[int32]string{
	0:  "Null",
	1:  "UINT8",
	2:  "UINT16",
	3:  "UINT32",
	4:  "UINT64",
	16: "FLOAT",
	17: "DOUBLE",
	32: "STRING",
	33: "BYTES",
}
var Command_Param_ParaType_value = map[string]int32{
	"Null":   0,
	"UINT8":  1,
	"UINT16": 2,
	"UINT32": 3,
	"UINT64": 4,
	"FLOAT":  16,
	"DOUBLE": 17,
	"STRING": 32,
	"BYTES":  33,
}

func (x Command_Param_ParaType) String() string {
	return proto.EnumName(Command_Param_ParaType_name, int32(x))
}

type Command struct {
	Type  Command_CommandType `protobuf:"varint,1,opt,name=type,enum=Report.Command_CommandType" json:"type,omitempty"`
	Paras []*Command_Param    `protobuf:"bytes,2,rep,name=paras" json:"paras,omitempty"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}

func (m *Command) GetParas() []*Command_Param {
	if m != nil {
		return m.Paras
	}
	return nil
}

type Command_Param struct {
	Type    Command_Param_ParaType `protobuf:"varint,1,opt,name=type,enum=Report.Command_Param_ParaType" json:"type,omitempty"`
	Npara   uint64                 `protobuf:"varint,2,opt,name=npara" json:"npara,omitempty"`
	Dpara   float64                `protobuf:"fixed64,3,opt,name=dpara" json:"dpara,omitempty"`
	Strpara string                 `protobuf:"bytes,4,opt,name=strpara" json:"strpara,omitempty"`
	Bpara   []byte                 `protobuf:"bytes,5,opt,name=bpara,proto3" json:"bpara,omitempty"`
}

func (m *Command_Param) Reset()         { *m = Command_Param{} }
func (m *Command_Param) String() string { return proto.CompactTextString(m) }
func (*Command_Param) ProtoMessage()    {}

type ControlReport struct {
	Tid          uint64   `protobuf:"varint,1,opt,name=tid" json:"tid,omitempty"`
	SerialNumber uint32   `protobuf:"varint,2,opt,name=serial_number" json:"serial_number,omitempty"`
	Command      *Command `protobuf:"bytes,3,opt,name=command" json:"command,omitempty"`
}

func (m *ControlReport) Reset()         { *m = ControlReport{} }
func (m *ControlReport) String() string { return proto.CompactTextString(m) }
func (*ControlReport) ProtoMessage()    {}

func (m *ControlReport) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func init() {
	proto.RegisterEnum("Report.Command_CommandType", Command_CommandType_name, Command_CommandType_value)
	proto.RegisterEnum("Report.Command_Param_ParaType", Command_Param_ParaType_name, Command_Param_ParaType_value)
}
